modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/MikeStorm03/QuickTeleports/issues"
logoFile="quickteleports.png"
credits="itsmeowdev, for programming, ideas, design and leading. \n MikeStorm03 /tpadeny, /back and /tpaccept <player> and no random accepting when /tpaccept"
authors="itsmeowdev, MikeStorm03"
[[mods]]
modId="quickteleports"
version="${version}"
displayName="QuickTeleports"
description='''
This mod adds a quick and easy way to send tp requests with /tpa and /tpaccept'''
[[dependencies.quickteleports]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="SERVER"